// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDamXGa9rZwiIdtguyQcHjVAqkMtywoPms',
    appId: '1:718399155489:android:542b64dad0bb2e2c73a260',
    messagingSenderId: '718399155489',
    projectId: 'we-connect-689f9',
    storageBucket: 'we-connect-689f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBu3V-Pn1TN4u0CnNEsXiB7mKztieb87g',
    appId: '1:718399155489:ios:a449064a1a16123673a260',
    messagingSenderId: '718399155489',
    projectId: 'we-connect-689f9',
    storageBucket: 'we-connect-689f9.appspot.com',
    androidClientId: '718399155489-9oq598tja28g3nv7s2tj48ufoqqfgjvq.apps.googleusercontent.com',
    iosClientId: '718399155489-148rc7efgjpevoqc6sski1dcvcq3anip.apps.googleusercontent.com',
    iosBundleId: 'com.example.weConnect',
  );

}